# Generated by Django 5.2.8 on 2026-01-08 01:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forum_conversation', '0014_alter_post_id_alter_topic_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GhostPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fake_username', models.CharField(blank=True, help_text='Nome falso para exibir no lugar do usuário real', max_length=150, null=True)),
                ('fake_avatar', models.ImageField(blank=True, help_text='Avatar falso para exibir', null=True, upload_to='ghost_avatars/')),
                ('post', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ghost_post', to='forum_conversation.post', verbose_name='Post original')),
            ],
        ),
    ]
